language: python
install:
  - git clone https://github.com/Z3Prover/z3.git && cd z3 && python scripts/mk_make.py --python && cd build/ && make && make install
  - pip install nose coverage
script:
  - export PYTHONPATH=$PWD/src:$PWD/test:$PWD/imp-interpreter
  - nosetests imp-interpreter/ test/ -v --with-coverage
notifications:
    email: false
sudo: false
