#!/usr/bin/env python

import sys

# Add imp-interpreter folder to sys.path
sys.path.append('imp-interpreter')

from imp_parser import *
from imp_lexer import *

from i_util import *

def usage():
    sys.stderr.write('Usage: iGen filename\n')
    sys.exit(1)

if __name__ == '__main__':
    if len(sys.argv) != 2:
        usage()
    filename = sys.argv[1]
    text = open(filename).read()
    tokens = imp_lex(text)
    parse_result = imp_parse(tokens)
    if not parse_result:
        sys.stderr.write('Parse error!\n')
        sys.exit(1)


    program = parse_parsed(parse_result)
    program = to_triple(program)
    
    print program


